#!/usr/bin/env bash

export DISPLAY=:0.0
 
function connect(){
  xrandr --output DP-1 --auto --right-of eDP-1
}
 
function disconnect(){
  xrandr --output DP-1 --off
}
 
xrandr | grep "DP-1 connected" &> /dev/null && connect || disconnect
